### ISSUE TITLE
Running integration tests from a nested project vs. a non-nested project

### ISSUE THREAD

**Issue by omega09** [jjohannes/gradle-plugins-howto#3]
Attached are my tests with gradle plugins and arquillian. This is the structure:
```
- zShrinkWrapTest
  | - gradlePlugins
      | - zplugins
  | - consumer
- consumer2
```
zShrinkWrapTest is the parent project
gradlePlugins is the plugins project (you recommend just using the gradle folder, same thing) and contains the zplugins project that has the plugins themselves. Not sure why there us a need to nest 1 project with the settings file and inside it another with the build file but I don't mind it.
consumer and consumer2 are the same project, only consumer is inside zShrinkWrapTest and consumer2 is next to it. They use the same single convention plugin inside zplugins.

The convention plugin uses the `jvm-test-suite` plugin so I can separate the tests and integration tests. The tests just uses Weld and doesn't require any special gradle task. The integration tests use arquillian and shrinkwrap. Shrinkwrap uses the gradle variant that uses the gradle tooling under the hood (BuildLauncher, ProjectConnection, GradleConnector). I'm also using Eclipse and buildship configured the projects for me (I don't change anything in eclipse manually). I use the junit platform launcher to try and run the tests through run as > junit test.

Here are the results:
| Run | consumer | consumer2 |
|--------|--------|--------|
| gradle `build` | works | works |
| gradle `test` | runs the test correctly | runs the test correctly |
| Eclipse test | runs the test correctly | runs the test correctly |
| gradle `integrationTest` | fails with error* | fails with error* |
| Eclipse integrationTest | runs the test successfully | fails with error** | 

\* error message
```
IntegrationTest > initializationError FAILED
    org.jboss.arquillian.container.spi.client.container.LifecycleException at CommonManagedDeployableContainer.java:107
        Caused by: java.lang.IllegalArgumentException at Environment.java:225
```

** error message
```
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.shrinkWrapTest.java-base'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:275)
	... 168 more
```

I'm having trouble understanding a couple things:
1. If building works then the plugin can be found in both projects but running the integration test through eclipse tells us that the plugin can not be found for consumer2 and can be be found for consumer. I don't understand why it can be found and then not be found and why in only one of them.
2. Gradle complains about arquillian/shrinkwrap when running `integrationTest` but eclipse shows it can be done (in consumer), so what is gradle missing that eclipse isn't?

Don't know if this is too much to ask but I'm not even sure where the problems come from. Is it my project setup, wrong plugin use, the gradle tooling, or arquillian/shrinkwrap? I hope some lessons for the general public can be derived from this.

* Careful with the arquillian.xml as it contains a path to my local wildfly server and if you try to run it you will need your own path. No configuration is required, just point to a wildfly downloaded folder.

[zShrinkWrapTest.zip](https://github.com/jjohannes/gradle-plugins-howto/files/14540984/zShrinkWrapTest.zip)
[consumer2.zip](https://github.com/jjohannes/gradle-plugins-howto/files/14540989/consumer2.zip)

**Comment by jjohannes** [comment]
@omega09 I had a quick look at the example you shared. Generally, I would try to get things running with Gradle directly first and in a second step check if the "running from Eclipse" works.

This is a very specific setup, because the `shrinkwrap-resolver-gradle-depchain` also talks to Gradle, through Gradle's [Tooling API](https://docs.gradle.org/current/userguide/third_party_integration.html#embedding), to get dependency information from Gradle. So you have several "layers" of Gradle invocations involved. 

Regarding your second error: I think it does not work for **consumer2**, because the folder of **consumer2** is not inside the build. This is a "not 100% supported" situation. When *shrinkwrap* talks to Gradle from **consumer2**, it operates inside the **consumer2** folder. Gradle then searches the folder hierarchy upwards for a "settings.gradle" to get the whole *build model* (which would include your `includeBuild("gradlePlugins")`). But it can't find it and thus assumes that *consumer2* is a stand-alone project without `settings.gradle` file. 
If you want a test, where **consumer2** is a separate outside project. You should add a `settings.gradle` to consumer2 itself with the corresponding `pluginManagement` block. 

Regarding your first error:  It does not look Gradle related problem to me, but I also failed to reproduce it. What I noticed in your reproducer is that there is no `arquillian.xml` in the `integrationTest/resources`. But I do not have much experience with these _jboss_ technologies.
